name: metrics
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: lowlighter/metrics@latest
        with:
          output_action: commit
          token: ${{ secrets.METRICS_TOKEN }}
          user: tejasholla
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_traffic: yes
