name: Update README with Wakatime Stats

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour, adjust as needed
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch Wakatime Stats
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          start_date=$(date -d "7 days ago" +%Y-%m-%d)
          end_date=$(date +%Y-%m-%d)
          curl -s -G \
            -d "api_key=${WAKATIME_API_KEY}" \
            -d "start=${start_date}" \
            -d "end=${end_date}" \
            https://wakatime.com/api/v1/users/current/summaries \
            -o wakatime.json

      - name: Print Wakatime Stats
        run: |
          echo "Wakatime JSON response:"
          cat wakatime.json

      - name: Update README
        run: |
          python update_readme.py

      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md wakatime.json
          git commit -m 'Updated README with Wakatime stats' || echo "No changes to commit"
          git push

      - name: Clean Up
        run: |
          rm wakatime.json
